Adding PR and issue tempaltes to fury-distro
sighupio/fury-distribution pull request #10
Opened 2022-01-21 13:12 UTC by nandajavarma

2022-01-21 17:32 UTC, ralgozino requested changes

2022-01-21 17:32 UTC, ralgozino commented on .github/ISSUE_TEMPLATE/bug_report.yaml
> +description: Report a bug encountered while operating Kubernetes
If this template will be the same for all the distro repos (the distro itself and the modules) maybe we should talk about operating kubernetes? we could just use "the software" maybe?

2022-02-18 15:21 UTC, nandajavarma commented
@ralgozino I have fixed the issue you mentioned. More discussion has to be done on this, I think. I have added a sample script here which can be used to sync the files to different modules. I do not have the permissions to test it out properly.

2022-02-21 19:36 UTC, ralgozino commented
Hi @nandajavarma ,Ping me on slack and let's see the permissions thing together

2022-07-05 13:13 UTC, closed without merging