Adding the contributing guidelines
sighupio/fury-distribution pull request #12
Opened 2022-01-31 10:04 UTC by nandajavarma

2022-01-31 10:37 UTC, ralgozino approved these changes
lgtm

2022-02-01 09:08 UTC, ralgozino requested changes
There are some links that need to be fixed

2022-02-21 19:26 UTC, ralgozino submitted a review, later dismissed
lgtm
feel free to merge @nandajavarma

2024-04-30 11:07 UTC, nutellinoit commented
Reopeing and reworking this PR

2024-10-29 16:21 UTC, closed without merging