feat: additional rules
sighupio/fury-distribution pull request #135
Opened 2023-10-16 13:37 UTC by Al-Pragliola

2023-10-17 06:05 UTC, alessiodionisi requested changes

2023-10-17 06:05 UTC, alessiodionisi commented on templates/preflight/onpremises/hosts.yaml.tpl
> +    {{- end }}
```suggestion
    {{- end }}

```

2023-10-31 11:07 UTC, omissis submitted a review, later dismissed

2023-10-31 11:08 UTC, omissis commented
testing so far went, well so +1-ing this one, but setting it back to needs review as we wait for the green light for merging it.

2023-11-03 16:52 UTC, omissis approved these changes

2023-11-03 16:53 UTC, merged