backport v1.27 to v1.26
sighupio/fury-distribution pull request #146
Opened 2023-12-20 11:04 UTC by alessiodionisi

2023-12-20 11:10 UTC, Al-Pragliola requested changes

2023-12-20 11:10 UTC, Al-Pragliola commented on README.md
> +| [Monitoring][tracing-module] | ![Version][tracing-version] | Tracing functionality based on Tempo |
Tracing*

2023-12-20 11:57 UTC, alessiodionisi commented on README.md
> +| [Monitoring][tracing-module] | ![Version][tracing-version] | Tracing functionality based on Tempo |
Also on 1.27

2023-12-20 14:02 UTC, omissis commented on README.md
> +| [Monitoring][tracing-module] | ![Version][tracing-version] | Tracing functionality based on Tempo |
fixed

2024-01-02 13:55 UTC, Al-Pragliola approved these changes
lgtm

2024-01-02 14:45 UTC, merged