feat: dex branding
sighupio/fury-distribution pull request #227
Opened 2024-06-24 13:00 UTC by Al-Pragliola

2024-07-16 07:53 UTC, ralgozino requested changes
Dex branding changes LGTM, but there are some other changes for gangplank included in this PR, is that ok?
Also, this PR is for changes that are still in draft or am I wrong?
- https://github.com/sighupio/fury-kubernetes-auth/pull/27

2024-07-16 08:15 UTC, Al-Pragliola commented
> Dex branding changes LGTM, but there are some other changes for gangplank included in this PR, is that ok? Also, this PR is for changes top the auth module that are still in draft or am I wrong?
> 
> * [feat: prepare v0.3.0 fury-kubernetes-auth#27](https://github.com/sighupio/fury-kubernetes-auth/pull/27)

change the PR's title to "feat: add support to auth module 0.3.0", same goes for the PR you linked that is not in draft state anymore, thanks for pointing it out

2024-07-16 08:17 UTC, ralgozino requested changes

2024-07-16 08:17 UTC, ralgozino commented on schemas/public/onpremises-kfd-v1alpha2.json
> +          "type": "string"
let's add a description to these fields and we are good to go :)

2024-07-17 08:27 UTC, ralgozino approved these changes
lgtm

2024-07-17 13:34 UTC, merged