Furyctl next integration
sighupio/fury-distribution pull request #30
Opened 2022-12-14 14:04 UTC by omissis

2022-12-20 10:55 UTC, omissis commented on kfd.yaml
> +    installer: v1.9.1
update to v1.10.0

2023-04-14 09:28 UTC, nutellinoit requested changes
overall LGTM, there are some missing points to be done:

- Write release note for v1.25.2 under `docs/releases`
- Write upgrade guide under `docs/upgrades` (the upgrade guide will only say that nothing changes module wise, but we added the alpha support for Furyctl)
- Add Furyfile.yml and kustomization.yaml on `releases/v1.25.2` (and maybe the new kfd.yaml)
- Update main README.md with the v1.25.2 version
- Update the compatibility matrix

2023-04-14 09:28 UTC, nutellinoit commented on kfd.yaml
> +version: v1.25.1
This version should be v1.25.2

2023-04-14 09:28 UTC, nutellinoit commented on source/manifests/networking/kustomization.yaml.tpl
> +---
This file is a leftover, I think should be removed

2023-04-14 16:04 UTC, nutellinoit approved these changes
LGTM!

2023-04-14 17:51 UTC, merged