feat(on-premises): node labels and annotations
sighupio/fury-distribution pull request #320
Opened 2024-12-05 11:22 UTC by ralgozino

## Summary

- Add the possibilty to set labels and annotations for both the control-plane nodes and the regular nodes.
- Added needed (optional) fields to the on-prem schema, with pattern validation.
- Added logic to the ansible playbook to set the labels and annotations on the nodes, and also remove them when deleted from the furyctl.yaml file. Checking against the saved state.

## Description

This PR extends the logic we had for setting the nodes roles and adds the possibility to set custom labels and annotations to both control-plane nodes and regular nodes for on-premises clusters.

We use `kubectl` commands instead of kubeadm/kubelet configuration because:
- kubeadm/kubelet configuration is set when joining the node.
- kubeadm/kubelet configuratino does not support setting some special labels, like the one that sets the node's role, and this is a use case that we wan't to cover.

Labels and annotations are defined at node group level (control-plane, workers, infra, etc. ) instead of at single node level, for simplicity and I believe most of the time this is what the user would want to do.

Labeling (or annotating) single nodes is not supported by this feature.

## Tests

The following manual tests were performed:

- [x] Adding labels and annotations that do not exist
- [x] Overwriting labels and annotations that already exist with a different value.
- [x] Adding labels and annotations with an empty value
- [x] Overwriting labels and annotations with an empty value
- [x] Node groups with no `labels:` propery defined.
- [x] Node groups with `labels:` propery defined but empty.
- [x] Annotations with spaces in the value.
- [x] Annotations and label keys with spaces are not allowed.
- [x] Setting the label that defines the node role works.
- [x] Create a cluster from scratch without custom labels and annotations, add some after creation, then delete them. All using the furyctl.yaml file.
- [x] Create a cluster from scratch with custom labels and annotations. Checked that they are present after creation.
- [x] Removing a label from the furyctl.yaml that has been manually deleted before from the cluster does not produce an error.
- [x] Removing an annotation from the furyctl.yaml that has been manually deleted before from the cluster does not produce an error.
- [x] Multi master cluster: labels and annotations are set on all nodes.
- [x] Multi node groups: labels and annotatoins are properly set to the nodes of the node group.
- [x] Execution of furyctl apply does not fail when the furyctl-config secret is manually deleted from the cluster.

## Future work

One possible improvement for the future is that furyctl already has downloaded and checked the previous cluster state (the furyctl-config secret). So it could make this information available to the template engine instead of downloading it again like we do now.

2024-12-05 13:31 UTC, speziato requested changes
seems legit overall! I pointed out just two typos, when I'm back home I will also try this locally

2024-12-05 13:31 UTC, speziato commented on schemas/public/onpremises-kfd-v1alpha2.json
> +          "description": "Optional additinal Kubernetes annotations that will be added to the control-plane nodes. Follows Kubernetes annotations format. **Existing annotations with the same key will
```suggestion
          "description": "Optional additional Kubernetes annotations that will be added to the control-plane nodes. Follows Kubernetes annotations format. **Existing annotations with the same key will be overwritten**.",
```

2024-12-05 13:31 UTC, speziato commented on schemas/public/onpremises-kfd-v1alpha2.json
> +          "description": "Optional additinal Kubernetes annotations that will be added to the nodes in this node group. Follows Kubernetes annotations format. **Existing annotations with the same key
```suggestion
          "description": "Optional additional Kubernetes annotations that will be added to the nodes in this node group. Follows Kubernetes annotations format. **Existing annotations with the same key will be overwritten**.",
```

2024-12-06 08:12 UTC, speziato submitted a review, later dismissed
LGTM! 🚀

2024-12-06 17:34 UTC, ralgozino commented
I added an example to the description and an `unrelased.md` file with the new feature.

2024-12-19 11:46 UTC, stefanoghinelli approved these changes
The changes are OK. 
In a future iteration, we could integrate a check based on Kubernetes'official well-known labels and annotations.

2024-12-19 14:33 UTC, merged