Feature: Add custom patches
sighupio/fury-distribution pull request #57
Opened 2023-02-27 15:31 UTC by luigibarbato

2023-03-03 11:17 UTC, nutellinoit requested changes
customPatches (your override field) should be under the `distribution` key, not outside

we also need to check the syntax for all the fields in the template, for example, we should put a 

```
patchesStrategicMerge: | 
    {{ .value }} #with some default identation 
```

See https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl#L34 as an example

patchesJson6902 should be an object array, see some example of patches json

secretGenerator and configGenerator, same as above

2023-03-09 15:41 UTC, nutellinoit commented
Proposal:

```
---
apiVersion: kfd.sighup.io/v1alpha2
kind: EKSCluster
metadata:
  # The name of the cluster, will be also used as a prefix for all the other resources created on AWS
  name: example
spec:
  distribution:
    customPatches:
      configMapGenerator: [] <- object array
      secretsGenerator: [] <- object array
      patchesJson6902: [] <- object array
      patchesStrategicMerge: [] <- string array
```

If the files are outside the kustomize project, the `--load_restrictor LoadRestrictionsNone` argument is mandatory on `kustomize build` furyctl commands, we need to check if this argument (or feature) is still present on version 4.x and 5.x (to future proof our solution)

Following an example with "all" the permutation we use in kustomization when creating clusters:

```yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../fury-kubernetes-aws/katalog/cluster-autoscaler/base


patchesStrategicMerge:
  - | 
    ---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        label1: value1
      name: cluster-autoscaler
      namespace: kube-system
  - | 
    ---
    apiVersion: v1
    kind: Service
    metadata:
      labels:
        label2: value2
      name: cluster-autoscaler
      namespace: kube-system
  - /Volumes/sighup_vol/github.com/sighupio/fury-distribution/patchtest.yaml

patchesJson6902: 
  - target:
      group: ""
      version: v1
      kind: Service
      name: cluster-autoscaler
      namespace: kube-system
    path: /Volumes/sighup_vol/github.com/sighupio/fury-distribution/patchjsontest.yaml
  - target:
      group: ""
      version: v1
      kind: Service
      name: cluster-autoscaler
      namespace: kube-system
    patch: |
          - op: add
            path: /metadata/labels/label3
            value: "value3"

configMapGenerator:
  - name: a-configmap
    files:
      - /Volumes/sighup_vol/github.com/sighupio/fury-distribution/config.example
  - name: b-configmap
    envs:
      - /Volumes/sighup_vol/github.com/sighupio/fury-distribution/env.example
      
secretGenerator:
  - name: a-secret
    files:
      - /Volumes/sighup_vol/github.com/sighupio/fury-distribution/config.example
  - name: b-secret
    envs:
      -  /Volumes/sighup_vol/github.com/sighupio/fury-distribution/env.example
```

2023-03-13 11:29 UTC, luigibarbato commented
> customPatches (your override field) should be under the `distribution` key, not outside
> 
> we also need to check the syntax for all the fields in the template, for example, we should put a
> 
> ```
> patchesStrategicMerge: | 
>     {{ .value }} #with some default identation 
> ```
> 
> See [`feature`/furyctl-next/templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl#L34](https://github.com/sighupio/fury-distribution/blob/feature/furyctl-next/templates/distribution/manifests/auth/resources/pomerium-policy.yml.tpl?rgh-link-date=2023-03-03T11%3A17%3A44Z#L34) as an example
> 
> patchesJson6902 should be an object array, see some example of patches json
> 
> secretGenerator and configGenerator, same as above

So, we should have a `customPatches` field for each module? e.g .`spec.distribution.modules.auth.pomerium.customPatches`

2023-03-13 11:31 UTC, nutellinoit commented
> So, we should have a `customPatches` field for each module? for example: `.spec.distribution.modules.auth.pomerium.customPatches`

Not right now, let's start with only the patches in the main kustomization.yaml

2023-03-14 10:02 UTC, luigibarbato commented
I used `patches` instead of `patchesJson6903` to follow https://github.com/kubernetes-sigs/kustomize/issues/2690

2023-03-27 15:12 UTC, omissis approved these changes
Tested. LGTM.

2023-03-27 15:13 UTC, merged