Add commonLabels to all KFD resources
sighupio/fury-distribution pull request #6
Opened 2021-09-23 12:16 UTC by nandajavarma

The labels will be useful to identify each resource as a part of KFD and which release of KFD is deployed. The assumption is that, the `vendor/` directory will be populated by `furyctl` so this installation is managed by `furyctl`. The version of `furyctl` is hard to assess at this point and hence not including that.

2021-09-29 10:07 UTC, lnovara requested changes
Honestly, I would change the `app.kubernetes.io/part-of` to something else since there is an high chance that some applications in the cluster will have a `app` label that might cause conflicts with Elasticsearch labels typing.

Also, adding @nutellinoit to have additional feedback.

2021-09-29 10:14 UTC, nutellinoit commented
> Honestly, I would change the `app.kubernetes.io/part-of` to something else since there is an high chance that some applications in the cluster will have a `app` label that might cause conflicts with Elasticsearch labels typing.
> 
> Also, adding @nutellinoit to have additional feedback.

There should be no problem with the new filter on fluentbit: https://github.com/sighupio/fury-kubernetes-logging/blob/master/katalog/fluentd/scripts/dedot.lua . Before doing this change i advise to do a manual test that everything is ok.

PS: BTW I have mixed feelings about forcing labels on the distribution level. Each module should know which is its distribution parent version. This way, we can find mixed versions on target clusters easily.

2021-09-29 10:21 UTC, lnovara commented
Additionally, we rarely use this repository while setting up clusters because with furyctl we rely on the fury-kubernetes-* repositories. But maybe this is going to change in the future.

2021-09-29 15:19 UTC, SIGHUP-C-3PO commented
@lnovara I will fix the `part-of` for sure.

About the labels being here or modules part, the release version of KFD will be sticky to a release of module. And according to the new plan, modules should have a dev/release cycles independent of KFD release. If module is being handled without this repo, ideally it would be good to not have KFD version number, but just the version of the module and of the components. This is just my perspective. I will have more discussions on this before merge.

2021-09-29 15:20 UTC, nandajavarma commented
@lnovara I will fix the part-of for sure.

About the labels being here or modules part, the release version of KFD will be sticky to a release of module. And according to the new plan, modules should have a dev/release cycle independent of KFD release. If module is being handled without this repo, ideally it would be good to not have KFD version number, but just the version of the module and of the components. This is just my perspective. I will have more discussions on this before merge.

2021-10-01 09:48 UTC, nandajavarma commented
According to @ipedrazas's suggestion regarding this, it is clear that it wouldn't make much sense to have KFD module version hard-coded into modules since it can be confusing and restrict a lifecycle on its own. Closing this in favor of opening PRs to add labels to modules.

2021-10-01 09:48 UTC, closed without merging