feature/60 allow per component node selector and tolerations overrides
sighupio/fury-distribution pull request #61
Opened 2023-03-02 15:35 UTC by omissis

- feat: introduce per-component node selector and tolerations for the aws module
- feat: introduce per-component node selector and tolerations for the auth module
- feat: introduce per-component node selector and tolerations for the dr module
- feat: introduce per-component node selector and tolerations for the ingress module
- feat: introduce per-component node selector and tolerations for the logging and monitoring modules
- feat: introduce per-component node selector and tolerations for the policy module

2023-03-03 10:46 UTC, nutellinoit approved these changes
Overall LGTM, good job @omissis 

Just one question ☝️

2023-03-03 11:45 UTC, omissis commented on templates/distribution/manifests/ingress/patches/infra-nodes.yml.tpl
> +        {{ template "nodeSelector" $cmArgs }}
will fix it, thanks!

2023-03-03 12:35 UTC, nutellinoit approved these changes
LGTM 🚀

2023-03-07 16:21 UTC, g-iannelli requested changes

2023-03-07 16:21 UTC, g-iannelli commented on pkg/schema/private/ekscluster_kfd_v1alpha2.go
> +type SpecDistributionModulesLoggingBanzai struct {
```suggestion
type SpecDistributionModulesLoggingOperator struct {
```

2023-03-07 16:21 UTC, g-iannelli commented on pkg/schema/private/ekscluster_kfd_v1alpha2.go
> +	Banzai *SpecDistributionModulesLoggingBanzai `json:"banzai,omitempty" yaml:"banzai,omitempty"`
```suggestion
type SpecDistributionModulesLogging struct {
	// Operator corresponds to the JSON schema field "operator".
	Banzai *SpecDistributionModulesLoggingOperator `json:"operator,omitempty" yaml:"operator,omitempty"`
```

2023-03-07 16:21 UTC, g-iannelli commented on pkg/schema/private/ekscluster_kfd_v1alpha2.go
> +type SpecDistributionModulesAwsSnapshotController struct {
```suggestion
type SpecDistributionModulesAwsEbsSnapshotController struct {
```

2023-03-07 16:21 UTC, g-iannelli commented on pkg/schema/private/ekscluster_kfd_v1alpha2.go
> +	SnapshotController *SpecDistributionModulesAwsSnapshotController `json:"snapshotController,omitempty" yaml:"snapshotController,omitempty"`
```suggestion
	SnapshotController *SpecDistributionModulesAwsEbsSnapshotController `json:"ebsSnapshotController,omitempty" yaml:"ebsSnapshotController,omitempty"`
```

2023-03-14 10:22 UTC, g-iannelli approved these changes
LGTM

2023-03-14 10:24 UTC, merged