feat: added coredns patch in terraform template
sighupio/fury-distribution pull request #65
Opened 2023-03-21 10:14 UTC by Al-Pragliola

2023-03-22 13:24 UTC, g-iannelli requested changes

2023-03-22 13:24 UTC, g-iannelli commented on templates/distribution/terraform/coredns.tf.tpl
> +  patch_data = {
```suggestion
  coredns_scheduling_patch = {
```

2023-03-22 13:24 UTC, g-iannelli commented on templates/distribution/terraform/coredns.tf.tpl
> +}
```suggestion
 coredns_scheduling_patch_as_json = jsonencode(local.patch_data)
}
```

2023-03-22 13:24 UTC, g-iannelli commented on templates/distribution/terraform/coredns.tf.tpl
> +    command = "${var.kubectl_path} patch deployment/coredns -n kube-system -p '${jsonencode(local.patch_data)}'"
```suggestion
    command = "${var.kubectl_path} patch deployment/coredns -n kube-system -p '${local.coredns_scheduling_patch_as_json}'"
```

2023-03-22 13:24 UTC, g-iannelli commented on templates/distribution/terraform/variables.tf
> +}
```suggestion
variable "kubectl_path" {
  type        = string
  description = "The path to the kubectl binary. By default, the one present in PATH is used"
  default = "kubectl"
}

```

2023-03-23 17:23 UTC, Al-Pragliola commented
Closing, as it's not relevant anymore.

2023-03-23 17:23 UTC, closed without merging