feat: add support to multiple schemas and the new `KFDDistribution` schema
sighupio/fury-distribution pull request #95
Opened 2023-05-19 14:47 UTC by alessiodionisi

SSIA

2023-06-01 13:25 UTC, nutellinoit commented
We should also change the behaviour with the certManager setting in the ingress module

Instead of 

```yaml
        nginx:
          # the tls section defines how the tls for the ingresses should be managed
          tls:
            # provider can be certManager, secret
            provider: certManager
        certManager:
          # the configuration for the clusterIssuer that will be created
          clusterIssuer:
            # the name of the clusterIssuer
            name: letsencrypt-fury
            # the email used during issuing procedures
            email: example@sighup.io
            # the type of the clusterIssuer, can be only http01, dns01 integration is not yet supported
            type: http01
```

We should swap type with solvers to make the user free to define the configuration

```yaml
        nginx:
          # the tls section defines how the tls for the ingresses should be managed
          tls:
            # provider can be certManager, secret
            provider: certManager
        certManager:
          # the configuration for the clusterIssuer that will be created
          clusterIssuer:
            # the name of the clusterIssuer
            name: letsencrypt-fury
            # the email used during issuing procedures
            email: example@sighup.io
            # solvers definition
            solvers: []
```

2023-06-12 07:25 UTC, nutellinoit commented
Opened a related issue: https://github.com/sighupio/fury-distribution/issues/105

2023-06-14 13:06 UTC, Al-Pragliola requested changes
Given the new defaults folder, we should delete the file furyctl-defaults.yaml

2023-06-14 13:06 UTC, Al-Pragliola commented on kfd.yaml
We should update develop to develop-next

```
  eks:
    version: 1.25
    installer: develop
```

2023-06-14 13:06 UTC, Al-Pragliola commented on schemas/private/ekscluster-kfd-v1alpha2.json
> +            "solvers"
Here we could reference an existing schema ( if it exists )

2023-06-29 10:28 UTC, omissis approved these changes
I left minor comments, LGTM

2023-06-29 10:28 UTC, omissis commented on kfd.yaml
> +    installer: develop-next
```suggestion
    version: 1.25
    installer: develop
```

2023-06-29 10:28 UTC, omissis commented on templates/distribution/manifests/networking/kustomization.yaml.tpl
> +{{- end }}
```suggestion
{{- end }}

```

2023-06-29 10:28 UTC, omissis commented on templates/distribution/manifests/networking/patches/infra-nodes-distro-cilium.yaml.tpl
> +        {{ template "tolerations" $ciliumArgs }}
```suggestion
        {{ template "tolerations" $ciliumArgs }}

```

2023-06-29 10:28 UTC, omissis commented on templates/distribution/terraform/velero.tf.tpl
> +{{- end }}
```suggestion
{{- end }}

```

2023-07-03 10:03 UTC, merged